terraform {
  required_providers {
    digitalocean = {
      source = "digitalocean/digitalocean"
    }
    local = {
      source = "hashicorp/local"
    }
  }
}

provider "digitalocean" {
  token = var.do_token
}

# Clave SSH compartida para todos los nodos
resource "digitalocean_ssh_key" "do_key" {
  name       = "do-ssh-key"
  public_key = file("~/.ssh/id_digitalocean_kubeadm.pub")
}

# Controlplane
resource "digitalocean_droplet" "cp01" {
  name     = "cp01"
  region   = "nyc3"
  size     = "s-2vcpu-4gb"
  image    = "debian-13-x64"
  ssh_keys = [digitalocean_ssh_key.do_key.fingerprint]
}

# Worker 1
resource "digitalocean_droplet" "wk01" {
  name     = "wk01"
  region   = "nyc3"
  size     = "s-2vcpu-4gb"
  image    = "debian-13-x64"
  ssh_keys = [digitalocean_ssh_key.do_key.fingerprint]
}

# Ansible inventory generated from the actual droplet IPs, so it can never go
# stale after a "terraform apply" recreates a droplet with a new address.
resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/ansible/hosts.ini"
  file_permission = "0644"

  content = <<-EOT
    # Generated by Terraform (main.tf) - do not edit by hand.
    # Run "terraform apply" to refresh it.

    [master]
    ${digitalocean_droplet.cp01.name} ansible_host=${digitalocean_droplet.cp01.ipv4_address} ansible_user=root

    [workers]
    ${digitalocean_droplet.wk01.name} ansible_host=${digitalocean_droplet.wk01.ipv4_address} ansible_user=root

    [all:vars]
    ansible_python_interpreter=/usr/bin/python3
  EOT
}

output "cp01_ip" {
  value = digitalocean_droplet.cp01.ipv4_address
}

output "wk01_ip" {
  value = digitalocean_droplet.wk01.ipv4_address
}
